// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using project;

#nullable disable

namespace Project.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260220102240_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("project.Babies", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("dateOfBirth")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("babies");
                });

            modelBuilder.Entity("project.Nurses", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<double>("workHours")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("nurses");
                });

            modelBuilder.Entity("project.Turns", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("babyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("dateOfTurn")
                        .HasColumnType("datetime2");

                    b.Property<int>("nurseId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("babyId")
                        .IsUnique();

                    b.HasIndex("nurseId");

                    b.ToTable("turns");
                });

            modelBuilder.Entity("project.Turns", b =>
                {
                    b.HasOne("project.Babies", "baby")
                        .WithOne("turn")
                        .HasForeignKey("project.Turns", "babyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("project.Nurses", "nurse")
                        .WithMany("turns")
                        .HasForeignKey("nurseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("baby");

                    b.Navigation("nurse");
                });

            modelBuilder.Entity("project.Babies", b =>
                {
                    b.Navigation("turn");
                });

            modelBuilder.Entity("project.Nurses", b =>
                {
                    b.Navigation("turns");
                });
#pragma warning restore 612, 618
        }
    }
}
